### ISSUE TITLE
Requires manage_options capability

### ISSUE THREAD

**Issue by roborourke** [pantheon-systems/google-map-gutenberg-block#20]
First off good work on the plugin :)

I've run into an issue because this is using the settings API endpoint, you can only use this block if you're an admin which isn't ideal!

I'd suggest adding a settings field to the general settings page and linking to that int the block instructions and perhaps and also having the option to `define()` the API key in code.

**Comment by ataylorme** [comment]
@roborourke thanks for opening the issue. I did not add a settings page as it seemed like a lot of additional overhead to manage one setting. Additionally, I'm not sure I agree with users who have lesser capabilities being able to change the API key.

One potential solution might be to only allow admins to manage the API key in the block settings and use `wp_localize_script` to pass any existing saved API so that users with lesser permissions can still create and use the map blocks. The API key could also be run through a filter before being passed to `wp_localize_script` so that it can be hardcoded/defined in the code as well.

Would that suffice for your needs or do you require the settings page as well?

**Comment by roborourke** [comment]
@ataylorme hey! You don't need an extra settings page necessarily, you can just add a settings field to an existing one like the writing settings screen for example.

I wasn't suggesting users without admin should be able to change the API key, just that the block completely fails to work in the editor if you're not an admin.

One thing to note with this approach, you'd need an admin to create the block somewhere initially to be able to add the API key before anyone else could use it.

It's not urgent as I've made a workaround branch on our fork at https://github.com/humanmade/google-map-gutenberg-block but I wanted to raise it here so you were aware. I can make a PR with that solution if it works for you.

**Comment by ataylorme** [comment]
@roborourke I took a look at [the changes in your fork](https://github.com/humanmade/google-map-gutenberg-block/pull/4/files) and that approach makes sense to me. If you submit a PR I can get it merged and release a new plugin version so you can install that rather than maintaining a fork.

**Comment by roborourke** [comment]
@ataylorme oh cool, will do :)
